framework:
  cache:
    app: cache.adapter.redis
    default_redis_provider: '%env(REDIS_URL)%'

    pools:
      # Cache pour les données Bungie API
      cache.bungie_api:
        adapter: cache.adapter.redis
        default_lifetime: 3600 # 1 heure

      # Cache pour les PGCR (Post Game Carnage Reports)
      cache.bungie_pgcr:
        adapter: cache.adapter.redis
        default_lifetime: 3600 # 1 heure

      # Cache pour les métadonnées des Strikes
      cache.bungie_strikes:
        adapter: cache.adapter.redis
        default_lifetime: 86400 # 24 heures

      # Cache pour les recherches de joueurs
      cache.player_search:
        adapter: cache.adapter.redis
        default_lifetime: 900 # 15 minutes

      # Cache pour le Manifest Bungie
      cache.bungie_manifest:
        adapter: cache.adapter.redis
        default_lifetime: 604800 # 7 jours